version: "3.2"
services:
  testdataserver:
    build: .
    ports:
      - 80:8000
    volumes:
      - ./db:/db
  atest:
    build: atest
    depends_on:
      - testdataserver
    environment:
      BASE_URL: http://testdataserver:8000
      ROBOT_OPTIONS: ""
    volumes:
      - ./atest/output:/atest/output
